### ISSUE TITLE
cant seem to get it to work when trying to find the seed of a server on 1.19

### ISSUE THREAD

**Issue by Fortnisphere** [19MisterX98/SeedcrackerX#113]
the server IP is play.blossomcraft.org if anyone can get the seed of the server btw the server world I use I cherry it might not be possible but if anyone can get it to work it would help a lot

**Comment by KINGS0FA** [comment]
Tulip blossom realm
Overworld: 7931013415653121332

**Comment by Gabe44t** [comment]
can anyone tell me the seeds to rest of the servers in blossom craft
1737597941447354906
3127093703288901182L
142574688076418497L

what do these belong to?
