### ISSUE TITLE
Seedcracker 1.18.2 issue

### ISSUE THREAD

**Issue by pSenju** [19MisterX98/SeedcrackerX#119]
I donwload seedcrackeX-2.12 for 1.18.2 but I wonder why everytime I join server or I create new world it keep Saving Wold then
crashing

-

**Comment by CJF2** [comment]
have the same problem

**Comment by Flopsyz** [comment]
Same bro.

**Comment by Flopsyz** [comment]
@19MisterX98 pls help

**Comment by 19MisterX98** [comment]
See #102

**Comment by CJF2** [comment]
i tried that but i could not get it to work. i have the same error as in that one but the fix did not work
