### ISSUE TITLE
Dont seem to collect any bits?

### ISSUE THREAD

**Issue by Piyaniist** [19MisterX98/SeedcrackerX#122]
Turned it on. 1.19. I can see only spawners with xray and getting near them or anywhere doesnt seem to help with seed.

**Comment by Hyphonic** [comment]
I get the same results when i use this mod on 1.19

**Comment by genericness** [comment]
> Turned it on. 1.19. I can see only spawners with xray and getting near them or anywhere doesnt seem to help with seed.

read. the. readme.
