### ISSUE TITLE
Error starting version 1.19

### ISSUE THREAD

**Issue by Hyperoo** [19MisterX98/SeedcrackerX#124]
Please try to solve it
[错误报告-2022-8-6_17.00.24.zip](https://github.com/19MisterX98/SeedcrackerX/files/9274739/-2022-8-6_17.00.24.zip)

**Comment by buiawpkgew1** [comment]
> 

mod列表

**Comment by buiawpkgew1** [comment]
> Please try to solve it [错误报告-2022-8-6_17.00.24.zip](https://github.com/19MisterX98/SeedcrackerX/files/9274739/-2022-8-6_17.00.24.zip)

mod列表

**Comment by Hyperoo** [comment]
![image](https://user-images.githubusercontent.com/58798629/183242738-173b3a3b-7bf0-484b-bc4f-74cc2f96a009.png)

**Comment by buiawpkgew1** [comment]
> ![image](https://user-images.githubusercontent.com/58798629/183242738-173b3a3b-7bf0-484b-bc4f-74cc2f96a009.png)

就3个？

**Comment by Hyperoo** [comment]
> > ![图片](https://user-images.githubusercontent.com/58798629/183242738-173b3a3b-7bf0-484b-bc4f-74cc2f96a009.png)
> 
> 就3个？

是的，只有三个

**Comment by Hyperoo** [comment]
> > ![图片](https://user-images.githubusercontent.com/58798629/183242738-173b3a3b-7bf0-484b-bc4f-74cc2f96a009.png)
> 
> 就3个？

找到原因了，使用了1.18的mod，这太蠢了

**Comment by buiawpkgew1** [comment]
> > > ![图片](https://user-images.githubusercontent.com/58798629/183242738-173b3a3b-7bf0-484b-bc4f-74cc2f96a009.png)
> > 
> > 
> > 就3个？
> 
> 找到原因了，使用了1.18的mod，这太蠢了

能不能关闭问题
