### ISSUE TITLE
Seed isn't the same

### ISSUE THREAD

**Issue by GitNat21** [19MisterX98/SeedcrackerX#128]
im in a server trying to get the seed, i get the seed but the spawn, nether and end is completely different from the server, i tried it on Normal, Amplified and Large Biome, idk what i did wrong and idk how to fix it

**Comment by 19MisterX98** [comment]
On paper servers the different dimensions can have different seeds. You need 5 end cities + end pillars to crack an end seed. Nether seed cracking is not supported in 1.18+
