### ISSUE TITLE
1.18.2 crash

### ISSUE THREAD

**Issue by ej6** [19MisterX98/SeedcrackerX#129]
i have tried loading up 1.18.2 but it would not work i thought maybe it was my client so i ran it by itself and it still wouldnt work im using fabric 

it crashes when i try to join a server i have not gotten a chance to look at the crash logs but when i do ill make a comment to this comment with the crash logs and hopefully the reason why the crash was happening just making this to let you know that this was a thing

**Comment by 19MisterX98** [comment]
delete the config. .minecraft/config/seedcrackerx.json. It doesnt like it when you used the mod on another version and change back.
