### ISSUE TITLE
Can I save the bits to file and start cracking on another pc (with no minecraft installed)?

### ISSUE THREAD

**Issue by aleck099** [19MisterX98/SeedcrackerX#136]
The cracking may take long time and cause heavy cpu usage, it should be aboe to run on another cpu

And, if I exited Minecraft client when the cracking isnt finished, will it start from where it stops last time?

**Comment by 19MisterX98** [comment]
it takes a few minutes on an average cpu. If your pc is too bad to handle that then Im sorry for you but I wont add those features
