### ISSUE TITLE
New 1.19.2 is out

### ISSUE THREAD

**Issue by HaraldsLV** [19MisterX98/SeedcrackerX#138]
I am playing on a server with my friends, but i hate slow progress and want to build some new farms (BUT they dont want to give the worlds seed). So i was wondering when would the update come for the next version of this mod. Allthou i dont know how long we will be playing on this server. I would love if this mod would update as fast as posible.(But i dont want u to hurry and be bothered by it :D )
Thanks !

**Comment by KINGS0FA** [comment]
works fine on 1.19.2
