### ISSUE TITLE
I found 10 structures on multiplayer, and it said no world seed found.

### ISSUE THREAD

**Issue by SeedCrackerXEnjoyer** [19MisterX98/SeedcrackerX#139]
I found 10 structures. I even cleared data and found another 10 with no luck (all 20 structures I found were shipwrecks).

I was wondering whether my version of SeedCrackerX was broken. I went on a new single player world (1.19.2) and teleported myself to liftable structures and SeedCrackerX found the correct seed.

Am I doing it wrong?
Is there something I should do that's different on multiplayer?

Info that might be useful: The server had Anti-Xray on diamonds (Displayed as stone when not in close range) and no other ore (Maybe netherite but I never tried)

The server is on 1.19

**Comment by 19MisterX98** [comment]
Some servers change structure generation to protect themselves against seed cracking. Usually it gets real nasty to crack those and the mod cant do it

**Comment by SeedCrackerXEnjoyer** [comment]
> Some servers change structure generation to protect themselves against seed cracking. Usually it gets real nasty to crack those and the mod cant do it

That's what I was thinking.

The server is simplyvannila.co

Is this server known for using custom seed gen?
