### ISSUE TITLE
Seed features finding

### ISSUE THREAD

**Issue by Some14u** [19MisterX98/SeedcrackerX#14]
Is it possible to add functionality to crack altered seed features (so-called magic numbers), as it described in the following article?
https://gitlab.com/taleden/MCeed-A

**Comment by 19MisterX98** [comment]
It is defenetly possible but changed structure salts are a niche scenario and if someone tried so hard to prevent seed cracking then they probably have their reasons.

**Comment by Some14u** [comment]
This is a typical scenario for any bukkit/spigot/paper server. If server owner decided not to post his world seed, then probably using your tool already counts against his wishes, though this doesn't prevent you from developing it :)
Can I ask you to add this possibility, please. It is already possible with taleden script, but it is so uncomfortable to use. I have to make a copy of the available part of the world, then scan it with something like amidst to acquire feature coordinates, download and install pyton with all extensions to run the script. That's a hell lot of labor.
Oh please! Sooner or later somebody would do this anyway.
