### ISSUE TITLE
Unable to crack seed

### ISSUE THREAD

**Issue by Adamiok** [19MisterX98/SeedcrackerX#151]
I am playing on a multiplayer server, using the latest stable release of seed cracker X. I have installed it using the latest release of fabric and added the fabric-api to my mods, with the seed. However, I am unable to crack the seed after finding the required number of structures. The seed cracker works on a singleplayer world (but there it is pointless, as I have `/seed`). Multiple tries failed, even got my friend to try. No crash report is present and debug mode shows no more output.

Server ip: `mc.lifestealsmp.com`

**Comment by DarkCIbrid** [comment]
They are either using custom terrain gen or you need to look for shipwrecks only because I found they work the best.

**Comment by Adamiok** [comment]
Well I looked for shipwrecks and it did not find the seed. Must be custom world gen or an anti cracking spigot plugin.
