### ISSUE TITLE
I installed mod 1.19.3, but I can't enter any commands in the chat.

### ISSUE THREAD

**Issue by StritFans** [19MisterX98/SeedcrackerX#162]
I installed mod 1.19.3, but I can't enter any commands in the chat. That is, I write, for example, /seed gui, but there is no such command. But here the structures are outlined, the xray works. Maybe you need a different version?

**Comment by StritFans** [comment]
I'm using google translate so sorry

**Comment by Dyiing** [comment]
On 1.19.3 the command changed from /seed to /seedcracker

**Comment by StritFans** [comment]
Okay, I'll try, thanks.
