### ISSUE TITLE
Nothing rendering and no data being collected

### ISSUE THREAD

**Issue by aaashleyyyy** [19MisterX98/SeedcrackerX#17]
Hello, I am trying to crack a nether seed on a Minecraft Server, this server does have an anti xray by the way. Whenever i load the game and go to a warped fungus I only ever get a hashed world seed, nothing more.  
![Screenshot (70)](https://user-images.githubusercontent.com/83358470/116794295-f14cea00-aa99-11eb-9adb-13c01664dbcf.png)

**Comment by aaashleyyyy** [comment]
Extra screenshots of the mod menu 
![Screenshot (71)](https://user-images.githubusercontent.com/83358470/116794370-83ed8900-aa9a-11eb-9d1d-c31f3b978c12.png)
![Screenshot (72)](https://user-images.githubusercontent.com/83358470/116794371-83ed8900-aa9a-11eb-9a0c-e1fd32821560.png)

**Comment by aaashleyyyy** [comment]
After some testing I have gotten this too work, closing now.

**Comment by Tiebe** [comment]
@aaashleyyyy how did you manage to make it work?
