### ISSUE TITLE
works when it wants to structures will never be found even if you're right next to them and Seed is always wrong

### ISSUE THREAD

**Issue by erh465t54thh54** [19MisterX98/SeedcrackerX#178]
works when it wants to structures will never be found even if you're right next to them and I did everything perfectly and I even got to work once on a solo world but the seed was incorrect stupidly  even if you're right on top of a shipwreck it doesn't find it for some reason fix ur shit

**Comment by ErrorNoInternet** [comment]
if you're unsatisfied then go get a refund
