### ISSUE TITLE
Says finished search with no results, reverting back to biomes 

### ISSUE THREAD

**Issue by DarkELPp** [19MisterX98/SeedcrackerX#18]
Hi i have all mods for perfectly working and dont work

**Comment by 19MisterX98** [comment]
I updated the mod a few hours ago. Are you using Version 0.2.6 or 0.2.7?

**Comment by DarkELPp** [comment]
0.2.7

**Comment by 19MisterX98** [comment]
Was the world generated in 1.16? SeedCrackerX only works with 1.16 versions by default.
Change the Version in your profile to 1.15 and try again If you aren't sure.

Some servers have custom overworlds. I cant guarantee for anything on them.
