### ISSUE TITLE
Crash when tried to join a multiplayer server

### ISSUE THREAD

**Issue by RODO83** [19MisterX98/SeedcrackerX#183]
Hello, as the title says i crash when i join a multiplayer server. Yes, i got the correct version of Minecraft and SeedcrackerX. I tried 1.19 fabric loader with SeedcrackerX version 2.13.
And it crash my game with this as the output:
[crash_report.txt](https://github.com/19MisterX98/SeedcrackerX/files/10610078/crash_report.txt)

**Comment by RODO83** [comment]
Nvm i just needed to delete the config file created by the mod.

**Comment by hermanyas** [comment]
Which config did you delete? I seem to have the same problem.
