### ISSUE TITLE
The Client shutdown with this mod.

### ISSUE THREAD

**Issue by Ac-Accelerator** [19MisterX98/SeedcrackerX#184]
The error infomation shows that:
 [Client Shutdown Thread/ERROR]: Mixin apply for mod seedcrackerx failed seedcracker.mixins.json:ClientPlayerEntityMixin from mod seedcrackerx -> net.minecraft.class_746: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on onSendCommand could not find any targets matching 'Lnet/minecraft/class_746;method_44098(Ljava/lang/String;Lnet/minecraft/class_2561;)V' in net.minecraft.class_746. Using refmap seedcrackerX-refmap.json [PREINJECT Applicator Phase -> seedcracker.mixins.json:ClientPlayerEntityMixin from mod seedcrackerx -> Prepare Injections ->  -> handler$zzm000$onSendCommand(Ljava/lang/String;Lnet/minecraft/class_2561;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]

other fabric mod can run perfectly,But I don't know why it can't run this mod ,how can i do to prevent this problem?

**Comment by Dyiing** [comment]
Looks like you're using the wrong Seedcracker version. Make sure you use 2.13.1-test for 1.19.3 and not 2.13

**Comment by Ac-Accelerator** [comment]
> Looks like you're using the wrong Seedcracker version. Make sure you use 2.13.1-test for 1.19.3 and not 2.13

thank you,i solved this problem by taking your advice.
