### ISSUE TITLE
make /seedcracker undetectable for servers

### ISSUE THREAD

**Issue by ItzSkyReed** [19MisterX98/SeedcrackerX#187]
![image](https://user-images.githubusercontent.com/93844414/218274929-5c94c164-d2f3-4a53-83a6-00cf22c1ae2e.png)
now, if you just write /seedcracker it sends to server, in my opinion it shouldn't

**Comment by ItzSkyReed** [comment]
may be make that /seedcracker will just open gui

**Comment by Cyclopropinon** [comment]
could be changed that anything starting with /seedcracker isnt sent to the server
