### ISSUE TITLE
finished dungeon search with no seeds

### ISSUE THREAD

**Issue by J9H2** [19MisterX98/SeedcrackerX#19]
It just keeps saying this, what do I do now?

**Comment by J9H2** [comment]
version 0.2.7

**Comment by J9H2** [comment]
and when I go to a dungeon it still doesnt do anything

**Comment by 19MisterX98** [comment]
Does this happen happen with different dungeons or just a specific one?

**Comment by J9H2** [comment]
it happens with every dungeon I come by, it just does nothing. It says this for every dungeon even when I mine all the walls

**Comment by 19MisterX98** [comment]
Does the server use a custom map/modified worldgen? Otherwise the mod normally at least find some structure seeds. 

Would you mind sharing the ip?

**Comment by ertugrul-cakici** [comment]
I have the same issue. Please help us

**Comment by var1nthon** [comment]
IP: amorycraft.com and thaicute.net "finished dungeon search with no seeds" Can't find a seed. I think he installed "AntiSeedCracker" Source: https://www.spigotmc.org/resources/antiseedcracker-1-15-1-16-x.81495/ Can you bypass this plugin? Please help us
