### ISSUE TITLE
seedcracer is not working

### ISSUE THREAD

**Issue by weymey5** [19MisterX98/SeedcrackerX#191]
Hello i have the seedcrackerX-2.13.1-test instaled but when i start up signleplayer, multiplayer it doesnt work i can see xraied objects but when i come to them nothing happens.

**Comment by Dyiing** [comment]
Nothings supposed to happen when you walk to them, the data will be stored (checked using `/seedcracker data bits`) and then the cracking process will begin after you've found 5 structures. 

Read [here](https://github.com/19MisterX98/SeedcrackerX#118x-and-higher) or watch [here](https://youtu.be/tKeEyx7jIE4?t=174)
