### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by StealthMeister1** [19MisterX98/SeedcrackerX#197]
Game crashes on Startup. No idea why. No log was given. No idea what to do.

**Comment by Dyiing** [comment]
Log always exists. `.minecraft/logs/latest.log`

**Comment by StealthMeister1** [comment]
> Log always exists. `.minecraft/logs/latest.log`

[latest.log](https://github.com/19MisterX98/SeedcrackerX/files/10945409/latest.log)

**Comment by Dyiing** [comment]
You're using the 1.19.3 version on 1.19.2. Try 2.13 instead

**Comment by StealthMeister1** [comment]
> You're using the 1.19.3 version on 1.19.2. Try 2.13 instead

Tried that earlier. Didn't work. None of the commands work except /seed d
ata and /seed gui. It also states that it's the 1.18 version in the /seed gui.

**Comment by Dyiing** [comment]
> It also states that it's the 1.18 version in the /seed gui.

That's because the cracking is the same in both versions, it does not matter. 

What other commands did you try? If you send an unfilled command it will return an error because you didn't provide any further input

**Comment by StealthMeister1** [comment]
Well /locate is the one I care the most about but apparently the command doesn't exist and I can't gather data without finding valid structures. Without that I apparently can't crack the seed.

> > It also states that it's the 1.18 version in the /seed gui.
> 
> That's because the cracking is the same in both versions, it does not matter.
> 
> What other commands did you try? If you send an unfilled command it will return an error because you didn't provide any further input

**Comment by Dyiing** [comment]
/locate is not a Seedcracker command. I assume you watched my video on it. I was simply demonstrating what the different structures look like by teleporting to them. You have to walk around and find the structures, like I showed in the second part of the video.

**Comment by StealthMeister1** [comment]
> /locate is not a Seedcracker command. I assume you watched my video on it. I was simply demonstrating what the different structures look like by teleporting to them. You have to walk around and find the structures, like I showed in the second part of the video.

What's the command to outline the structures? Is it /seed render outlines ON ?

**Comment by StealthMeister1** [comment]
I just found a shipwreck and got no data bits from it so now I'm just confused.

**Comment by StealthMeister1** [comment]
Also. Anti Xray doesn't seem to work.

**Comment by StealthMeister1** [comment]
Anyone able to help with this??

**Comment by ItzSkyReed** [comment]
help is in discord

**Comment by StealthMeister1** [comment]
> help is in discord

I don't have the discord. You could've just helped me here but aight.

**Comment by StealthMeister1** [comment]
Anyone able to help? Please?

**Comment by StealthMeister1** [comment]
I give up on this.
