### ISSUE TITLE
Dungeon finder does not work in multiplayer paper servers

### ISSUE THREAD

**Issue by Wattville** [19MisterX98/SeedcrackerX#20]

**Comment by Wattville** [comment]
these are the plugins
![Screen Shot 2021-05-29 at 10 51 03 AM](https://user-images.githubusercontent.com/85033762/120080029-d014f480-c06b-11eb-9174-07d9e9ed7d4c.png)

**Comment by 19MisterX98** [comment]
Paper has not patched this.
If the mod cant find dungeons, then its a problem with Orebfuscator. It has a proximity feature that hides block entitys like spawners if they are too far away. Just find one manually, go to it so the game loads the spawner and type "/seed finder reload". This will scan all chunks again and actually find the spawner. 

If seedcracker can find spawners and just cant crack the seed then the selected version in the seedcracker menu is probalby not compatible with the version of the server

**Comment by Wattville** [comment]
ok, do you know a bypass?

**Comment by 19MisterX98** [comment]
> Just find one manually, go to it so the game loads the spawner and type "/seed finder reload". This will scan all chunks again and actually find the spawner.
