### ISSUE TITLE
seedcracker no longer uploads to database

### ISSUE THREAD

**Issue by skermiebroTech** [19MisterX98/SeedcrackerX#218]
only shows upload failed

**Comment by 19MisterX98** [comment]
you need a valid mc session. Offline sessions dont work

**Comment by DraconicNEO** [comment]
> you need a valid mc session. Offline sessions dont work

I tried uploading a seed I got from a server but it doesn't seem to be uploading either, I am using a valid MSA session, does it just take time to update the sheet or are there issues with uploading as of late?

**Comment by 19MisterX98** [comment]
Were over 10 players online while you cracked it

**Comment by DraconicNEO** [comment]
> Were over 10 players online while you cracked it

I think so but I'm not 100% sure.
