### ISSUE TITLE
looking for world seeds that are possible if the world uses a random seed and they are all invalid

### ISSUE THREAD

**Issue by GOLDENSMITE** [19MisterX98/SeedcrackerX#23]
i attempt crack a 1.16.5 version server seed and accord with video and detected 7 result of the seed finally,then i apply these seed and they are all incorrect.this is the server ip：play.junyestudio.com.

**Comment by aaashleyyyy** [comment]
I think your talking about the "found structure seeds."  Those aren't the actual seed those are structure seeds. the actual seed will appear under the structure seeds after ~5 seconds.  If it errors, walk out of those chunks, rejoin, and wait till it finds a new dungeon, if it still doesn't work, try it a few more times.  If it still doesn't work after that, then report back to here.

**Comment by aaashleyyyy** [comment]
I tried cracking the seed on this server for you, they have some plugin that prevents seed cracking.  Unlucky.

**Comment by 19MisterX98** [comment]
crack the seed with biomes. the hashed seed method is blocked by a plugin but biome cracking should still work as long as biomes are natural.

**Comment by GOLDENSMITE** [comment]
> crack the seed with biomes. the hashed seed method is blocked by a plugin but biome cracking should still work as long as biomes are natural.

then i should only open biome finder toggle and find all the biome of the server?
