### ISSUE TITLE
Dungeon cracking

### ISSUE THREAD

**Issue by Luc2002** [19MisterX98/SeedcrackerX#25]
Hi I tried dungeon cracking on a server, it keeps loading and saying finished without finding seeds. I tried more then 20 different dungeons. 
Then i started a single player world, the same issue. I know the last version in 1.16 worked in the nether as well, but here it doesn’t seem to work or am i missing something?

**Comment by 19MisterX98** [comment]
Most servers run on a modified server.jar (mostly spigot or paper).
A small subset of those modified server.jars prevent dungeon cracking.
Another reason could be that the terrain is from an older version.
Dungeon cracking should always work in Singleplayer.
