### ISSUE TITLE
Using Seedcracker in the nether on a multi version server

### ISSUE THREAD

**Issue by SebasDezz** [19MisterX98/SeedcrackerX#28]
Its not starting to crack while in the right biome with all the resources
also do you have a discord?

**Comment by SebasDezz** [comment]
![image](https://user-images.githubusercontent.com/86245849/122783055-83f75180-d2b1-11eb-8298-46211604c872.png)

**Comment by 19MisterX98** [comment]
maybe there is no fungus that meets the requirements. I would suggest finding another warped forest

**Comment by SebasDezz** [comment]
I've went through about 6/7 forests but only got a max of 1 or 2 trees to show up,
i guess it kind of works
