### ISSUE TITLE
finished dungeon search with no seeds

### ISSUE THREAD

**Issue by NOTred88** [19MisterX98/SeedcrackerX#29]
the server is running on freemcserver.net, it runs on purpur with no plugins added
no matter what dungeon I search from it always gives me this error

**Comment by ObscenityIB** [comment]
@NOTred88 purpur specialises in customisation, literally every type of generation can be modified in the config.

**Comment by 19MisterX98** [comment]
> 
> 
> @NOTred88 purpur specialises in customisation, literally every type of generation can be modified in the config.

Yep, purpur has a wide variety of settings that can stop seed crackers. There are some parts of world generation that probably are still vulnerable though even with a custom config.
