### ISSUE TITLE
Couldn't find the nether seed

### ISSUE THREAD

**Issue by VortexR6** [19MisterX98/SeedcrackerX#3]
I tried to find the nether seed of a server that I play and everytime I found a warped fungus it said "couldn't find a seed for this fungus" and Idk why

**Comment by 19MisterX98** [comment]
It used the fungus positions in the chunk to reverse to seeds. You found a good fungus but the mod got false information about the other fungi in the chunk(Mine those extra stems). Another reason could be that a lot of fungus trunks are chopped down(place stems in those positions so the mod recognices them again). I set some bounds to the cracker so in theory you could get a chunk where there are so many fungi that the cracker cant find the start anymore.

**Comment by VortexR6** [comment]
I've been trying again, I chopped extra stems, tried to put it back and nothing happened, I could get it in SP but not here, could you help me to get it if I give you the IP?

**Comment by 19MisterX98** [comment]
I'm not doing that anymore unless there is something really strange going on. Can you send a screenshot of the chunk?

**Comment by VortexR6** [comment]
![2021-01-29_15 44 43](https://user-images.githubusercontent.com/78196748/106310080-cefcc380-6241-11eb-8dad-8a26e3e37971.png)
![2021-01-29_15 44 40](https://user-images.githubusercontent.com/78196748/106310412-492d4800-6242-11eb-8eb0-994706383227.png)

**Comment by 19MisterX98** [comment]
![Screenshot_20210130-010647](https://user-images.githubusercontent.com/41451155/106339711-ab646800-6297-11eb-9dec-e5e40e514a1e.png)
[](url)There are defenetly some funguses missing.
The bottom part of their stems needs to touch netherrack/warped nylium.
Can you try adding those stems?

**Comment by VortexR6** [comment]
![2021-01-29_22 54 10](https://user-images.githubusercontent.com/78196748/106341733-0b99e080-627d-11eb-8e0e-3d1db6414521.png)
![2021-01-29_22 53 57](https://user-images.githubusercontent.com/78196748/106341748-1b192980-627d-11eb-8310-08716d336db9.png)
In these two I tried to add the stems, remove some netherrack and add again, and nothing worked :((

**Comment by VortexR6** [comment]
:/
