### ISSUE TITLE
Game fails to start when on 1.21

### ISSUE THREAD

**Issue by Auxurious** [19MisterX98/SeedcrackerX#305]
I have the correct API, fabric 1.21 and java 21. Game starts fine without seedcracker, but when i put it into the mods folder and try to start the game, it gives me error code 1 (Something went wrong)

**Comment by D3XX3R** [comment]
Have you tried the [pre-release build](https://github.com/19MisterX98/SeedcrackerX/releases/tag/prerelease)?
I've been able to load in and crack a seed.

**Comment by Auxurious** [comment]
Haven't, ill try it out. Thanks for the reply

**Comment by Auxurious** [comment]
World generation gets stuck at 100% with the pre-release build.
<img width="514" alt="ggs" src="https://github.com/19MisterX98/SeedcrackerX/assets/172764316/d2eafa99-231d-4bb2-ab9b-f6ee20f12662">

**Comment by D3XX3R** [comment]
That's weird. I can load into both sp and mp.
Can you share your log file?

**Comment by Auxurious** [comment]
I tried replicating it and now it works. I guess the last time was just a fluke
