### ISSUE TITLE
Doesn't find the seed in the End dimension  

### ISSUE THREAD

**Issue by Mamin-gamer** [19MisterX98/SeedcrackerX#31]
My end dimension was generated and then server changed to Vanilla, then Fabric, then back to Spigot. By this time, we explored nether, found elytras and generated some chunks in the end. 
I assume that the mod requires to visit the main island in order to collect data from pillars, but I believe that it was generated with different seed. (Basically, 2 seeds were generated and pillars from 1st seed, most of other end including new chunks from another seed). 
I don't Know how this happened, but I assume it will never find the seed since pillars are already generated. 

Is there anything I can do manually to make it work or it all depends on pillars and its hard-coded? 

Many thanks

**Comment by 19MisterX98** [comment]
Its possible to find an endseed without pillars but its really not worth the effort.

**Comment by Mamin-gamer** [comment]
Not worth the effort? How hard it it or what does it require to achieve it?

**Comment by 19MisterX98** [comment]
input data and run https://github.com/hube12/GPUExample

ask neil if you have any questions about it https://discord.gg/anHsq24nqt
