### ISSUE TITLE
SeedCrackerX Not capturing shipwrecks properly.

### ISSUE THREAD

**Issue by PericoSpart** [19MisterX98/SeedcrackerX#319]
Version 1.21
On multiplayer
Issue:
Found an igloo, right after that an ocean monument (not liftable). found a shipwreck but couldn't get captured, I had to rejoin for SeedCrackerX to recognize it. It worked on other servers but this time it isn't capturing the structure. I have no fabric api installed.

**Comment by PericoSpart** [comment]
+ No resourcepacks are being used.

**Comment by PericoSpart** [comment]
Fabric api missing could be the issue. I will notify if it's fixed.

**Comment by PericoSpart** [comment]
Captured a jungle temple, I realized I had debug on, could be the issue.

**Comment by PericoSpart** [comment]
Debug was not the issue, it still did not capture shipwrecks correctly. Issue is still not resolved.

**Comment by PericoSpart** [comment]
If you rejoin and the shipwreck doesnt get captured, I found out that if you rejoin multiple times it gets recognized.

**Comment by PericoSpart** [comment]
When did I spam?

**Comment by PericoSpart** [comment]
When did I spam?

**Comment by PericoSpart** [comment]
Also I have to do reload everytime I see a shipwreck? Why? Why not just try and fix the issue?

**Comment by optimizeee** [comment]
@PericoSpart that server you're in uses anti xray and it has chest in its hidden blocks (which seedcracker uses to detect it) so if u go near it and reload then it works
