### ISSUE TITLE
Support for cracking seeds in the Nether

### ISSUE THREAD

**Issue by epixinvites** [19MisterX98/SeedcrackerX#35]
The server I am currently on has different seeds for the Overworld, Nether and The End. It is best if you could crack the seeds for Nether and The End separately. Thank you.

**Comment by 19MisterX98** [comment]
Nether seeds can be cracked using warped fungi, end seeds via end pillars + end structures. I need to fix end seed cracking for 1.17 though

**Comment by epixinvites** [comment]
@19MisterX98 but the thing here is even if i go to the nether, it doesn't automatically start cracking the seed.
