### ISSUE TITLE
Nether seed cracker is inaccurate

### ISSUE THREAD

**Issue by epixinvites** [19MisterX98/SeedcrackerX#36]
So, I'm on a server, Minecraft 1.17 and I ran the seed cracker in the nether, it gave me a "Fungus seed" and a "Structure seed". I tested these two seeds as the seed in a singleplayer world and it is wrong. And this "End Pillar Seed", what am I supposed to do with it, its just 5 numbers.

**Comment by Dyiing** [comment]
> I tested these two seeds as the seed

You tested the fungus/structure seeds? These are not equivalent to the world seed unless it returns "this structure seed is also usable as the world seed". I would assume that these only hold data about the particular fungus or tree generation patterns, similar with the end pillar seed. The seed you want will say "Found **world** seed".

In my personal experience it requires a couple warped biomes before it will correctly find a seed from the nether.

**Comment by epixinvites** [comment]
@Dyiing it return [xxx] is also usable as the world seed, i tested it in my sp world, it is inaccurate.

**Comment by Snowad14** [comment]
Just trying to find other, it happens to me not to find good immediately but after some trees I find the world seed
