### ISSUE TITLE
Seed

### ISSUE THREAD

**Issue by MinecraftVR** [19MisterX98/SeedcrackerX#37]
It wont locate the seed and it keeps failing the dungeon search. I have 207/32 bits

**Comment by dedokok** [comment]
it's just that on many servers dungeon cracker has already been found

**Comment by aaashleyyyy** [comment]
/seed data clear, rejoin, also make sure you dont have too much stuff enabled.  I only enable dungeons and biomes.  If that doesnt work after 3 different dungeons, the seed cant be cracked cuz some anti seed cracking generation thingy.

**Comment by aaashleyyyy** [comment]
well this guy's dead

**Comment by 19MisterX98** [comment]
Tru
