### ISSUE TITLE
Cant fownd the new mod update.

### ISSUE THREAD

**Issue by Godwhitelight** [19MisterX98/SeedcrackerX#4]
can you relese the new version please? i dont have it on my releses

**Comment by 19MisterX98** [comment]
this is the newest version and it is released
https://github.com/19MisterX98/SeedcrackerX/releases/tag/2.6

**Comment by 19MisterX98** [comment]
[
![Unbenannt](https://user-images.githubusercontent.com/41451155/106399483-2b660b80-6419-11eb-9599-19c6381a1adb.PNG)
](url)
