### ISSUE TITLE
Can you just keep the thing off by default and we can manually turn it on?

### ISSUE THREAD

**Issue by Kraken12112** [19MisterX98/SeedcrackerX#40]
Every fucking time I join a server, no matter the server, it turns on and lags my fucking game like crazy when shortcutting to dungeons I have a server and play on servers with custom generation so since it can't find the seed, it keeps on looking and keeps on lagging the hell out of my game. Just keep it off by default and when we want to use it, we'll turn it on with /seed crack, if we leave a server, it turns back off.

**Comment by 19MisterX98** [comment]
You can turn it of in the profile tab. I would also recommend just creating a separate instance if you use multimc

**Comment by Kraken12112** [comment]
What profile tab?

**Comment by 19MisterX98** [comment]
Watch the end of my tutorial https://youtu.be/8ytfZ2MXosY
