### ISSUE TITLE
does not work on multi player 

### ISSUE THREAD

**Issue by sricharan1027** [19MisterX98/SeedcrackerX#41]

**Comment by 19MisterX98** [comment]
https://plshelpm.ee/plshelpmee.png

**Comment by sricharan1027** [comment]
oops yes i mean when i login in to a a mc server and it gets the seed then i go to seedmapper and type the seed in the do find end city it gives me the cords then i use baritone be coz i am lazy as shit then i go there and there is no end city :(

**Comment by 19MisterX98** [comment]
can you create a singleplayer world with the seed? Just to confirm that its wrong

**Comment by Jackson-Harrison** [comment]
Based on your comment I'm going to guess that you are not using the mod properly and are trying to use the hashed seed that prints in chat when you first log into the dimension. Please watch the tutorial video if you want to learn how to use the mod.

**Comment by sricharan1027** [comment]
i mean i confirmed it it works un  singleplayer but not in mulitplayer see  file i have attached
![Screenshot (691)](https://user-images.githubusercontent.com/89474696/131964115-9f566d40-7d0b-4b38-9f7f-d07ea876ffb9.png)
![Screenshot (692)](https://user-images.githubusercontent.com/89474696/131964138-f2103b20-7631-4a34-9c2e-3cf2455424f0.png)
![Screenshot (693)](https://user-images.githubusercontent.com/89474696/131964305-46e8ebde-6e76-4133-b1cd-6e2626bbb300.png)
![Screenshot (694)](https://user-images.githubusercontent.com/89474696/131964329-2a67b481-b051-485b-a26f-91bc8c6e52e3.png)

**Comment by 19MisterX98** [comment]
The hashed seed is not the world seed. Pls watch the tutorial
