### ISSUE TITLE
problem world seed not found 

### ISSUE THREAD

**Issue by sricharan1027** [19MisterX98/SeedcrackerX#44]
bro i told you only hasted seed is coming there is not world seed

**Comment by aaashleyyyy** [comment]
you need to enable the stuff with mod menu you dumby, and you have to walk around until the find a dungeon, or open warped fungus, etc.  these videos will help you  https://www.youtube.com/watch?v=8ytfZ2MXosY https://www.youtube.com/watch?v=HKjwgofhKs4

**Comment by sricharan1027** [comment]
bruh it tells world seed not found

**Comment by sricharan1027** [comment]
i play on 1.17.1

**Comment by 19MisterX98** [comment]
Was the terrain generated in 1.17.1 or was the server updated from earlier versions?
You want to crack an end dimension seed, right? Are you sure you only collected data from the end?

**Comment by sricharan1027** [comment]
yes i do only want to crack end seed yes it was generated in 1.17.1

**Comment by 19MisterX98** [comment]
Collect pillar data, end city data and randomly spawning end gateway data. The mod should start cracking the seed if you got enough. The resulting structure seed can be used as world seed.

**Comment by sricharan1027** [comment]
yes i asked one of my admin friends why is the seed cracker not working he said that we made a plugin that does not allow to crack the seed :(

**Comment by aaashleyyyy** [comment]
> yes i asked one of my admin friends why is the seed cracker not working he said that we made a plugin that does not allow to crack the seed :(

close issue noob

**Comment by 19MisterX98** [comment]
I bet it's still possible but it's not worth my time
