### ISSUE TITLE
Update Please?

### ISSUE THREAD

**Issue by Wolfy8198** [19MisterX98/SeedcrackerX#49]
Could you update the 1.16.5 version and add the updates for the 1.17 version please? I play on an Origins server and I need the 1.16.5 version. I would like it to be updated with the latest tweaks, but if you can't do it or don't have time I understand.

**Comment by Wolfy8198** [comment]
The problem is that because the mod itself is for 1.17 I can't load in
minecraft. The origins mod is for 1.16.5

**Comment by 19MisterX98** [comment]
Use an external seedcracker then. For example https://github.com/WearBlackAllDay/SeedCandy
