### ISSUE TITLE
1.18

### ISSUE THREAD

**Issue by aradum3** [19MisterX98/SeedcrackerX#50]
how soon will it be available for 1.18 and do you plan on updating?

**Comment by 19MisterX98** [comment]
no eta but Im working on it

**Comment by erxson** [comment]
thanks

**Comment by Shufimanden** [comment]
thanks man:)

**Comment by SoullessHunter** [comment]
Hey, thanks for already working on it man. I'll be hyped until it's released.

**Comment by Tarantyl** [comment]
thanks for your hard work

**Comment by 9fmanay2** [comment]
Thanks god 🙏🏻💪🏻

**Comment by RannyBergamotte** [comment]
Can't wait! Ty for your hard work!
