### ISSUE TITLE
Error on startup 

### ISSUE THREAD

**Issue by yaukari** [19MisterX98/SeedcrackerX#53]
![image](https://user-images.githubusercontent.com/75146973/145663846-dabab9c8-db75-407d-876e-a549394e8290.png)
`The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'fabric-containers-v0'!
Exit Code: -1`

**Comment by SoullessHunter** [comment]
There is no 1.18 Version yet.

**Comment by buiawpkgew1** [comment]
https://github.com/buiawpkgew1/SeedcrackerX/releases/tag/exp
