### ISSUE TITLE
Inaccurate ore position

### ISSUE THREAD

**Issue by fathulamin00** [19MisterX98/SeedcrackerX#61]
The cracker found the seed, I find 3 shipwreck, 1 monument, 1 jungle temple.
When I use OreSim and enter the world seed, I try mining using the Xray, somehow the ore wasnt there.
Am i doing something wrong?

**Comment by 19MisterX98** [comment]
Oresim isnt 100% accurate. Make sure that the seed is correct. Generate a singleplayer world with the seed and see if the ores match there

**Comment by fathulamin00** [comment]
> Oresim isnt 100% accurate. Make sure that the seed is correct. Generate a singleplayer world with the seed and see if the ores match there

Okay this is really weird, I created a singleplayer world with the seed obtained by seed cracker. In single player, the ore was there exactly where oresim predict. It was the exact same world as in the server I joined. But the ore wasnt there using oresim in the server

**Comment by 19MisterX98** [comment]
Some servers change ore locations :(

**Comment by fathulamin00** [comment]
By any chance, do you know any workaround this ?

**Comment by 19MisterX98** [comment]
Nope, it's likely that the server uses papers custom feature seeds. They are random and not connected to the world seed
