### ISSUE TITLE
Read

### ISSUE THREAD

**Issue by ThatOneOcto** [19MisterX98/SeedcrackerX#62]
I'm at the dungeon but it won't give the seed

**Comment by ThatOneOcto** [comment]
I'm on 1.18.1

**Comment by 19MisterX98** [comment]
Dungeon cracking doesn't work anymore in 1.18
Usage guide now:
https://github.com/19MisterX98/SeedcrackerX/releases/tag/2.11.4

**Comment by ThatOneOcto** [comment]
I'm at a dessert temple, it didn't give me the seed

**Comment by ThatOneOcto** [comment]
Same with shipwreck

**Comment by erxson** [comment]
read guide again, please
