### ISSUE TITLE
Seed Not Showing

### ISSUE THREAD

**Issue by EhBCz** [19MisterX98/SeedcrackerX#63]
Hi, so I load up the seed cracker in a multiplayer server, but it doesnt show the seed, or anything. can someone help?

**Comment by InfoTeddy** [comment]
It's not as simple as that. Unless a server admin is willing to give you the seed, or you're on a really old version of Minecraft, the seed isn't something that can be easily obtained automatically (this is especially true in 1.18).

Read the [usage guide](https://github.com/19MisterX98/SeedcrackerX/releases/). You'll need to run around the world and find enough structures (desert pyramids, jungle temples, witch huts, shipwrecks, igloos, pillager outposts, etc.) to collect enough information to crack the seed. When a structure is recognized, there'll be xray outlines showing it.
