### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by Waldo-ayy** [19MisterX98/SeedcrackerX#66]
Error only happens when SeedcrackerX is installed.

[latest.log](https://github.com/19MisterX98/SeedcrackerX/files/7944451/latest.log)

**Comment by 19MisterX98** [comment]
oh yeah, I was lazy and basically created a race condition when joining a world quickly after starting the game. At least I think thats the case

**Comment by Waldo-ayy** [comment]
hmm I tried waiting a couple of minutes but it still crashes when loading a world so I don't think it's related to that
