### ISSUE TITLE
I cant find the seed. Can you please help sir ?

### ISSUE THREAD

**Issue by mayureshpandharikar** [19MisterX98/SeedcrackerX#7]
![IMG-20210222-WA0032](https://user-images.githubusercontent.com/64885463/108754808-6e288880-756c-11eb-8cad-831e00c1e9e0.jpg)
![IMG-20210222-WA0033](https://user-images.githubusercontent.com/64885463/108754811-6ff24c00-756c-11eb-91fc-0532a822dbc3.jpg)
![IMG-20210222-WA0037](https://user-images.githubusercontent.com/64885463/108754815-708ae280-756c-11eb-8961-b3b69265c82d.jpg)
![Screenshot_20210222-231436](https://user-images.githubusercontent.com/64885463/108754818-71237900-756c-11eb-9d28-4d257cbb86b8.jpg)
I found 5 seeds and none of them is right.
Is it due to tlauncher?
I dk have official too so should i try it?

**Comment by 19MisterX98** [comment]
Its probably a paper-mc server. They fixed dungeon cracking. There is no way for you to crack those seeds until tree-cracker is user friendly enough for the broad public.

**Comment by mayureshpandharikar** [comment]
Okay. Thank you!
