### ISSUE TITLE
Seed cracker is working in singleplayer.But in multiplayer,the whole game is crashing....

### ISSUE THREAD

**Issue by procrafter820** [19MisterX98/SeedcrackerX#71]
Seed cracker is working in singleplayer.But in multiplayer,the whole game is crashing....
 They have VULGAN Anticheat
 Here is the crash report
[crash-2022-03-05_21.22.00-client.txt](https://github.com/19MisterX98/SeedcrackerX/files/8190994/crash-2022-03-05_21.22.00-client.txt)

**Comment by procrafter820** [comment]
I use fabric

**Comment by procrafter820** [comment]
[latest.log](https://github.com/19MisterX98/SeedcrackerX/files/8190997/latest.log)
Here is latest.log

**Comment by 19MisterX98** [comment]
fixed, forgot to close the issue
