### ISSUE TITLE
There is no /seed version 1.18.2 & it doesn't work with SeedMapper 1.15.1

### ISSUE THREAD

**Issue by asvalias** [19MisterX98/SeedcrackerX#78]
Title says it all. I don't really know if you're guys working together or not with xpple but I managed to notice that your mod and his don't work together at the moment.

**Comment by 19MisterX98** [comment]
The 1.18.2 stuff is a library that I need to update. Can you send a crashlog regarding the issue with seedmapper? Xpple and I don't work together but we know eachother from discord.

**Comment by asvalias** [comment]
> The 1.18.2 stuff is a library that I need to update. Can you send a crashlog regarding the issue with seedmapper? Xpple and I don't work together but we know eachother from discord.
[latest.log](https://github.com/19MisterX98/SeedcrackerX/files/8372409/latest.log)
I might guess what you're looking for is
com.mojang.brigadier.exceptions.CommandSyntaxException: Version "1.18.2" was not found.
( that's from file )
