### ISSUE TITLE
Non txt saved file type will show Finished search with no result found when structure requirements met

### ISSUE THREAD

**Issue by liekos47** [19MisterX98/SeedcrackerX#84]
Non txt saved file in the %appdata%\Roaming.minecraft\config\SeedCrackerX saved structures will show Finished search with no result (my suspection).

Created single world and saved file is txt but trying to crack 2b2t test server showed as 240 file type with file name 'test.2b2t.org_51.161.19.240'.

Added .txt extension will still re-create 240 file type.

**Comment by 19MisterX98** [comment]
The "Finished search with no result" message is part of the cracking process and not influenced by the file naming. All files should be saved as txt. Are you sure this isnt because of hidden file extensions in your file explorer?

**Comment by blord0** [comment]
The server port is included after the name which does strange stuff as ntfs doesn't know how to handle ":" in file names. So it creates an alternate data stream file. The 2b2t file would be saved under "test.2b2t.org_51.161.19.240:25565.txt:$DATA".
You can check for yourself if you open cmd in the directory and type "dir /R"

**Comment by 19MisterX98** [comment]
Welp, didn't know that ntfs doesn't allow : 
I've been using linux for some time now and i didn't expect something like that. Will fix when i have time

**Comment by Artoria2e5** [comment]
Can confirm. Luckily enough it did work for saving and loading as long as you are on NTFS, but it does make editing a lot harder.
