### ISSUE TITLE
The world seed in this dimension is different

### ISSUE THREAD

**Issue by reth06** [19MisterX98/SeedcrackerX#85]
I use seedcrackerx on 1.18.2 minecraft spigot server, and this message appear. is there any solution
![issue](https://user-images.githubusercontent.com/101316165/165842161-7305d99f-1095-457a-9c3b-c3dc73884e3c.png)
?

**Comment by 19MisterX98** [comment]
In itself that isn't a problem. Just a notification that two worlds from the same server use different seeds

**Comment by reth06** [comment]
But i still can crack the seed right?
