### ISSUE TITLE
Seed cracker isnt working in shipwreck does this is because of some antixray plugins?

### ISSUE THREAD

**Issue by GamychampPie** [19MisterX98/SeedcrackerX#94]

**Comment by GamychampPie** [comment]
can u make seed cracker that it can bypass orebfuscator plugin

**Comment by 19MisterX98** [comment]
Just go to a structure and do /seed finder reload. That should work in most cases

**Comment by GamychampPie** [comment]
> Just go to a structure and do /seed finder reload. That should work in most cases

yeah it worked but sometimes i just gone to an shipwrek it worked but when i leave the server certain times and it shows /seed data restore but after sometimes it doest work

**Comment by GamychampPie** [comment]
its show no structures from previous session

**Comment by 19MisterX98** [comment]
The mod only stores data from the previous session. let's say you find a structure and reconnect. Then it will prompt you. If you don't restore the structure and then reconnect again the data is lost

**Comment by GamychampPie** [comment]
ok
i got a new problem i have 53 out of 40 lifting bits and its showing u need to find more structures

**Comment by GamychampPie** [comment]
![2022-06-03_15 43 46](https://user-images.githubusercontent.com/84699434/171835468-b3697312-b623-4774-8b1d-a0eaf82d1f1f.png)
this
